import { Inter } from 'next/font/google'
import '../globals.css'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Your Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
        <Navbar/>
        <div className='max-w-4xl mx-auto p-4 '>

        {children}
        </div>
        </main>
        </body>
    </html>
  )
}
